{{- $scn := .Values.storageClassName }}
{{- $volumeBasePath := .Values.volumeBasePath }}
{{- $count := .Values.replicaCount | int }}
{{- range $index := until $count }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-etcd-{{$index}}
  labels:
    type: local
  finalizers:
    - kubernetes.io/pv-protection
spec:
  capacity:
    storage: 5Gi
  hostPath:
    path: {{ $volumeBasePath }}{{ $index }}  
    type: ''
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: {{ $scn }}
  volumeMode: Filesystem
---
{{- end }}
