apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: {{ .Values.namespace }}
  labels:
    app: etcd
spec:
  ports:
  - port: 2379
    name: client
  - port: 2380
    name: peer
  clusterIP: None
  selector:
    app: etcd
