apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ default "default-storage-class" .Values.storageClassName }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
